### ISSUE TITLE
Errors in files.

### ISSUE THREAD

**Issue by Krot666** [Euno/eunowallet#1]
I can not finish compiling my wallet due to the lack of these files.
![screenshot_2](https://user-images.githubusercontent.com/33595988/43034246-4b5064da-8d03-11e8-9a67-8753856a4575.png)

**Comment by eunodevteam** [comment]
You need to compile the LevelDB infront of compiling the wallet .

-->> Level DB
cd ~/eunowallet/src/leveldb
chmod +x build_detect_platform
make libleveldb.a libmemenv.a
