### ISSUE TITLE
RPC keep crashing

### ISSUE THREAD

**Issue by MNtank** [Euno/eunowallet#2]
Hello,

I have installed Euno wallet inside mine server and trying to access it from webbase application but the rpc keep crashing.

The follow conf have add inside mine coin conf.

rpcuser=xxxxx
rpcpassword=xxxxx
rpcport=21333
rpcallowip=127.0.0.1

when this error happend it just give timeout.

I don't have this problem with other wallets.

**Comment by arrie1992** [comment]
Should be fixed in the new wallet
